#!/usr/bin/env bash

buildlocal () {
  cd $1
  if [ "$1" = eacgi ]; then
    chmod +x secp384r1.cgi
  fi
  docker build -t "127.0.0.1:5000/$1" .
  docker push "127.0.0.1:5000/$1"
  docker save "127.0.0.1:5000/$1" > "$1".tar
  microk8s ctr image import "$1".tar
  cd ..
}


chmod +x ACCOUNT-api || echo "WARN: no default backend ACCOUNT-api found found in $(pwd)"
cp ACCOUNT-api /srv/persist/ACCOUNT/bin/ || echo "WARN: the default backend was not copied to /srv/persist/ACCOUNT/bin/"

echo "Checking for registry."

reglistener=$(docker container ls | awk '{print $2}' | grep registry | wc -l)
if [ $reglistener = 1 ]; then
  echo "local docker registry found..."
else
  echo "No local registry found, starting up local registry."
  docker run -d -it --restart unless-stopped  -p 5000:5000 registry
fi


buildlocal eaasapi
buildlocal eanginx
buildlocal eaproxy
buildlocal eatransfer


echo
echo -e "\e[32mRepo build complete!\e[0m"
echo
