apiVersion: apps/v1
kind: Deployment
metadata:
  name: eaasapi-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eaasapi-d
  template:
    metadata:
      labels:
        app: eaasapi-d
    spec:
      containers:
      - name: eanginx
        image: localhost:5001/eaasapi-d/eanginx
        ports:
        - name: https
          containerPort: 443
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginxmount
        - mountPath: /var/www/html/ACCOUNT
          name: eapersist
        - mountPath: /var/tmp
          name: vartmp

      - name: eaasapi
        image: localhost:5001/eaasapi-d/eaasapi
        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginxmount
        - mountPath: /var/www/html/ACCOUNT
          name: eapersist
        - mountPath: /var/tmp
          name: vartmp
        - mountPath: /root/.gnupg
          name: gpgmount
        - mountPath: /usr/local/bin/
          name: binmount

      volumes:
       - name: eapersist
         hostPath:
           path: /srv/persist/ACCOUNT/www
           type: Directory
       - name: vartmp
         hostPath:
           path: /srv/persist/ACCOUNT/var/tmp
           type: Directory    
       - name: nginxmount
         hostPath:
           path: /srv/persist/ACCOUNT/log
           type: Directory    
       - name: gpgmount
         hostPath:
           path: /srv/persist/ACCOUNT/gpg
           type: Directory    
       - name: binmount
         hostPath:
           path: /srv/persist/ACCOUNT/bin
           type: Directory    
